version: '2'
services:
  php:
    build: ./build/php
    ports:
     - 80:80
    volumes:
     - ./build/apache:/etc/apache2/sites-enabled
     - ./tmp/log/apache:/var/log/apache2
     - /d/www:/var/www/html
